version: '2'
services:
  hello-world:
    image: dlvr/saltconfdemo:latest
    stdin_open: true
    tty: true
    entrypoint:
    - java
    - -Dspring.config.location=/tmp/src/main/resources/application-lab.properties
    - -jar
    - /tmp/build/libs/hello-world-0.0.1-SNAPSHOT.jar
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.pull_image: always
