version: '2'
services:
  hello-world:
    image: dlvr/saltconfdemo:{{ config.tag }}
    stdin_open: true
    tty: true
    entrypoint:
    - java
    - -jar
    - /tmp/target/hello-springboot-1.3.5.RELEASE.war
    - -D
    - /tmp/src/main/resources/application-{{ config.environment }}.properties
    ports:
    - 8080:8080/tcp
    dns:
    - {{ rancher_dns }}
    labels:
      io.rancher.container.pull_image: always
