name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install pip
      run: sudo apt-get install python3 python3-pip && sudo pip3 install cloudsmith-cli
    - name: Build with Maven
      run: mvn package
